### ISSUE TITLE
sql error when going to admin control panel 

### ISSUE THREAD

**Issue by shep65** [oxpus/Feed-Reader#1]
Hi
Was testing feed reader tonight
Got mysql error, when trying to access admin control panel. Now unable to disable extension to clear error

General Error
SQL ERROR [ mysql4 ]

Table 'kiteboarder_X.SFNC_FEEDS' doesn't exist [1146]

SQL

SELECT id FROM SFNC_FEEDS WHERE enabled_displaying = 1

Is there any way to work around this so I can access the admin control panel and disable the extension. I will test it on another forum first

Thanks

Tony

**Comment by oxpus** [comment]
Corious....
To disable the Ext change in the database table phpbb_ext the value ext_active to 0 within the dataset for oxpus/feed. 
Then clear the folder cache/ in your forum and you should have access to the Acp.

**Comment by shep65** [comment]
Hi

Thanks for your help
The problem was resolved
I have set up a test forum now and just started to use the extension again
As there is now support for this, I will let you know what settings I am running
I am not very familiar with using feeds, so this is all learning for me




Not sure how to use the news tickers?
I will be posting feeds from various vimeo channels, will it be possible for the link to be displayed in the tags that will enable the video to be shown, instead of just the link, so that it can be played on the forum page?

I have had one news item from each of the three feeds posted on my forum, in this image it shows that the feed is “posting” but not “displaying” is this correct?



Looks good so far and will be great on my forum for adding content, I run a sport forum, so a lot of people involved in the sport use vimeo for news

Many thanks

Tony

**Comment by oxpus** [comment]
The Feed Reader just uses pure text feeds, no media content.
So you can't fetch e. g. videos from live feeds.

The ticker funktion will just display the feed titles on the board page as a real ticker.

**Comment by shep65** [comment]
Hi
I got another error today
I added a news ticker, cannot access admin panel again
Will send screen shot as I'm on my phone

Tony

**Comment by oxpus** [comment]
I've updated the event listener.
Please replace all extension files and retry.
