### ISSUE TITLE
Twig_Error_Loader in cron mode

### ISSUE THREAD

**Issue by wcz-txp** [oxpus/Feed-Reader#3]
When running in cron mode (/bin/phpbbcli.php cron:run) this error message appears, after posting the first new post from one of the rss feeds in the list:

```
  [Twig_Error_Loader]                                     
  Unable to find template "bbcode.html" (looked into: ).
```

After that cron is not ending properly, not releasing cron lock, what can be manually released in using `/bin/phpbbcli.php config:set cron_lock 0`, but anyway only one post per cron session is not how it should work.
I already tried to put bbcode.html in every style directory, but it didn't help.

**Comment by oxpus** [comment]
Sorry, but the feed cron job was _not_ designed to run as an external cron job!
The cron options of the feed reader only uses the internal phpBB cron functions to run after each page load, not just by viewing the forum index (the index option of the feed reader).

The template file bbcode.html (normaly stored in styles/stylename/template/) can not be found without using the "normal" phpBB template system. And the phpBB template will not be included completely in phpbbcli.php...

**Comment by wcz-txp** [comment]
ah ok, I tried to avoid `Tried to redirect to potentially insecure url.` messages on page load. This message appears from time to time, but I don't know what is causing this, because no one of my rss feeds has a redirection or something else.

**Comment by oxpus** [comment]
This is a bug in phpbb itself...

**Comment by wcz-txp** [comment]
ok, thanks for explanation ...
