### ISSUE TITLE
HTTP 500 on manage feed

### ISSUE THREAD

**Issue by OminiData** [oxpus/Feed-Reader#4]
i gets a http 500 when i go to manage feed 
on 3.2.1

**Comment by oxpus** [comment]
HTTP 500 is an error produces by your server not by the extension.
It can have many reasons...

**Comment by OminiData** [comment]
hmm strange as i had instaled it as all my other extensions and is only the managed feed that are an issue and not the general setting

**Comment by oxpus** [comment]
It may be that the error occurs only in the feed reader extension, but a http 500 error is always from the server.
Either a service is not installed correctly or not active at all.
Try select an other method to fetch the feeds.
Not every server supports every method offered by the extension.

**Comment by castordor** [comment]
I get the same error, here is the error message:

Fatal error: Class 'phpbb\controller\provider' not found in /home/user/public_html/forums/ext/oxpus/feed/acp/main_module.php on line 26

**Comment by oxpus** [comment]
ACP module fixed for this error.
Maybe other 500er errors are fixed, too?!?
